import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from "./components/AuthProvider";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "utalkto",
  description: "Generated by webDev2776",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${inter.className} min-h-screen flex flex-col`}>
          <Navbar />
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
